apiVersion: v1
kind: Service
metadata:
  name: detection
  namespace: default
  labels:
    app: detection
spec:
  selector:
    app: detection
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
